config/routes.rb
Sfbay::Application.routes.draw do
  
  resources :scrape, :only => [:create, :index] do
    get :scrape_date
    post :search, on: :collection
  end

  root 'scrape#index'

end

app/models/scrape_record.rb
class ScrapeRecord < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scrape_controller.rb
require 'scrape'

class ScrapeController < ApplicationController

  def create
    begin
      scrape_result_obj = ScrapeResult::Scrape.new
      car_details = scrape_result_obj.data_scraping
      car_details.each do |car_detail|
        record = ScrapeRecord.find_or_initialize_by(title: car_detail[:title])
        record.update(title: car_detail[:title], mileage: car_detail[:mileage].to_i)
      end
      flash[:success] = 'Car mileage is stored' 
    rescue
      flash[:error] = 'Error: Car mileage is not stored'
    ensure
      redirect_to scrape_index_path
    end
  end

  def index
    @mileages = ScrapeRecord.all
  end

  def search
    if params["search"].blank?
      redirect_to scrape_index_path 
    else
      @mileages = ScrapeRecord.where("mileage = ?", params["search"])
      @search = params["search"]
      render 'index'
    end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrape_helper.rb
module ScrapeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sfbay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'shared/nav' %>
  <%= render partial: 'shared/flash' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/scrape/index.html.erb
<table class='table table-striped table-bordered sortable' id="mytable">
  <thead>
    <th> Title </th>
    <th> Mileage </th>
  </thead>
  <tbody>
    <% @mileages.each do |mileage| %>
      <tr>
        <td><%= mileage.title %></td>
        <td><%= mileage.mileage %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/shared/_nav.html.erb
<div class="bs-example">
    <nav role="navigation" class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Home", root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Scrape Data", scrape_index_path, method: :post, :confirm => 'Do you want?' %></li>
          </ul>
          <%= form_tag search_scrape_index_path, method: :post, class: "navbar-form navbar-left"  do %>
            <%= text_field_tag :search, @search, class: "form-control", placeholder: "Search by Mileage" %>
            <%= submit_tag "Search", class: "btn btn-default" %>
          <%end%>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>